# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    disallow_search_engine_index: false
    annotations:
        enabled: false
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
    translator:
        fallbacks: [ 'fr' ]
    enabled_locales: [ 'fr' ]
    #esi: true
    #fragments: true
#    assets:
#        version: 'v1.1' # ou utiliser un hash généré automatiquement
#        version_format: '%%s?%%s'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
