twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        googleRecaptchaPkey: '%gg_recaptcha_pkey%'

when@test:
    twig:
        strict_variables: true
