back:
    resource: ../../src/Controller/Back/
    type: attribute
    prefix: /admin
    name_prefix: "back_"

front:
    resource: ../../src/Controller/Front/
    type: attribute
    name_prefix: "front_"

kernel:
    resource: ../../src/Kernel.php
    type: attribute