# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    email_support: "%env(resolve:EMAIL_SUPPORT)%"
    email_contact: "%env(resolve:EMAIL_CONTACT)%"
    gg_recaptcha_pkey: "%env(resolve:GG_RECAPTCHA_PKEY)%"
    gg_recaptcha_skey: "%env(resolve:GG_RECAPTCHA_SKEY)%"
    .container.dumper.inline_factories: true
    debug.container.dump: false

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $emailContact: "%email_contact%"
            $googleRecaptchaSkey: "%gg_recaptcha_skey%"
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
